"""methon contact getIcon

Revision ID: 113ad434f97b
Revises: e8046266c6d3
Create Date: 2021-06-21 06:05:53.368396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '113ad434f97b'
down_revision = 'e8046266c6d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
