"""empty message

Revision ID: 2d38215af43e
Revises: 
Create Date: 2021-05-22 01:20:06.008345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d38215af43e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dIcons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('desc', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tAbout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public', sa.DateTime(), nullable=False),
    sa.Column('about', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tContacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tPortfolio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo', sa.String(length=255), nullable=False),
    sa.Column('desc', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tUsers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=12), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tContactIcons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('f_contact', sa.Integer(), nullable=True),
    sa.Column('f_icon', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['f_contact'], ['tContacts.id'], ),
    sa.ForeignKeyConstraint(['f_icon'], ['dIcons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tContactIcons')
    op.drop_table('tUsers')
    op.drop_table('tPortfolio')
    op.drop_table('tContacts')
    op.drop_table('tAbout')
    op.drop_table('dIcons')
    # ### end Alembic commands ###
