"""empty message

Revision ID: a57d27a7d63b
Revises: 3fb7df5f29f9
Create Date: 2021-06-21 05:58:54.379266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a57d27a7d63b'
down_revision = '3fb7df5f29f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
