"""methon contact getIcon v2

Revision ID: ce6f43cbc51f
Revises: 113ad434f97b
Create Date: 2021-06-21 06:28:04.476652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce6f43cbc51f'
down_revision = '113ad434f97b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
