"""methon contact

Revision ID: e8046266c6d3
Revises: a57d27a7d63b
Create Date: 2021-06-21 05:59:20.300666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8046266c6d3'
down_revision = 'a57d27a7d63b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
